### ISSUE TITLE
Просьба создать файлы для тестирования банкнот в папке Support

### ISSUE THREAD

**Issue by PugachA** [AntonDyrdin/esgp#14]
Антон создай эти файлы в Support, чтобы не исправлять каждый раз в коде под себя пути. А то у нас нет доступа к текущем путям

**Comment by AntonDyrdin** [comment]
Допишу код для автоматического создания резервной копии и пропишу путь к оригинальному файлу.

**Comment by AntonDyrdin** [comment]
Прописаны пути к оригинальным файлам в папке "S:\ДЕЖУРНЫЙ ИНЖЕНЕР СМЕНА\" !!!
Теперь при каждом нажатии кнопок "Добавить запись в файл..." создаётся его резервная копия в папке "Резервные копии", которая находится в одной папке с исполняемым (.exe) файлом. При чём изменения в оригинальном файле не сохраняются в автоматически (во избежание косяков).
