### ISSUE TITLE
Счётчики

### ISSUE THREAD

**Issue by AntonDyrdin** [AntonDyrdin/esgp#17]
Цитата из автоматически сформированного письма:
"Показания счетчиков: Передать показания
Счетчик1: 25225
Счетчик2: 265
Счетчик3: 130"
**_Не приведут ли к путанице такие названия счётчиков? Как на это смотрит Белоконь И.?_**

**Comment by PugachA** [comment]
Такие письма уже были отправлены и успешно обработаны Белоконь И.. Я считаю путаницы не должно быть. Счетчики вводятся по порядку.
