### ISSUE TITLE
Метод формирования письма по банкноте в купюроприёмнике.

### ISSUE THREAD

**Issue by AntonDyrdin** [AntonDyrdin/esgp#2]
Есть метод - buildLetterUnrecognized(), он принимает все необходимые данные об инциденте с нераспознанной купюрой, объединяет их по шаблону с заготовкой письма и возвращает полный текст письма.
Нужно по образцу этого метода сделать метод для формирования письма по банкноте в купюроприёмнике (будет другая заготовка).
Добавить вызов этого метода в событие нажатия кнопки "Сформировать письмо" на вкладке "Инциденты с банкнотами" [button7_Click()] с учётом логики

**Comment by spartak22** [comment]
Сделано
