### ISSUE TITLE
Зачисление на новые рекзвизиты

### ISSUE THREAD

**Issue by PugachA** [AntonDyrdin/esgp#7]
Можно оставить заполнение на новые реквизиты руками. Но хочется это автоматизировать. Предлагаю, при выборе в combobox "На другие реквизиты" делать активным rtb, к который можно будет вставить из Helpdesk строку с примером платежа.

**Comment by AntonDyrdin** [comment]
я бы оставил ручное заполнение, так как поиск примера платежа в help/desk даже усложнит процесс

**Comment by PugachA** [comment]
Будем заполнять руками
